# Generated by Django 4.1 on 2022-09-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variation",
            old_name="cerated_date",
            new_name="created_date",
        ),
    ]
