# Generated by Django 4.1 on 2022-09-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_cerated_date_variation_created_date"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
