# Generated by Django 4.1 on 2022-10-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    (None, "Choose Gender"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("Rather not say", "Rather not say"),
                ],
                max_length=100,
            ),
        ),
    ]
