# Generated by Django 4.1 on 2022-09-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="Payment_id",
            new_name="payment_id",
        ),
    ]
