# Generated by Django 4.1 on 2022-09-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_rename_payment_id_payment_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
