# Generated by Django 4.1 on 2022-10-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_payment_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
