# Generated by Django 4.1 on 2022-10-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
