# Generated by Django 4.1 on 2022-10-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_remove_orderproduct_variation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.payment",
            ),
        ),
    ]
